name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - name: Install dependencies
      run: flutter pub get
    - name: Check for flutter errors
      run: flutter doctor
    - name: Run tests
      run: flutter pub run test
    - name: Web Application building
      run: flutter build web
